name: Gatus ECS Workflow

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/destroy.yml'
  
  workflow_dispatch:
    
concurrency:
  group: "${{ github.repository }}-${{ github.ref_name }}"
  cancel-in-progress: false
permissions:
  id-token: write
  contents: read
  
jobs: 
    build:
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v5.1.1
          with:
            aws-region: eu-west-2
            role-to-assume: arn:aws:iam::826199897019:role/oidc-role
        - name: log into ECR
          run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 826199897019.dkr.ecr.eu-west-2.amazonaws.com

        - name: terraform setup
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.14.0"

        - name: build image
          run: docker build -t gatus-ecr ./app/gatus

        - name: tag Docker image
          run: docker tag gatus-ecr:latest 826199897019.dkr.ecr.eu-west-2.amazonaws.com/gatus-ecr:${{ github.sha }}

        - name: terraform initialise
          run: terraform init
          working-directory: infra

        - name: plan ecr repo
          run: terraform plan -target=module.ecr.aws_ecr_repository.gatus_ecr
          working-directory: infra
          
        - name: apply ecr repo
          run: terraform apply -target=module.ecr.aws_ecr_repository.gatus_ecr -auto-approve
          working-directory: infra

        - name: push Docker image
          run: docker push 826199897019.dkr.ecr.eu-west-2.amazonaws.com/gatus-ecr:${{ github.sha }}

        - name: terraform fmt
          run: terraform fmt -check
          working-directory: infra

        - name: terraform validate
          run: terraform validate
          working-directory: infra
        
        - name: tflint setup
          uses: terraform-linters/setup-tflint@v6
          with:
            tflint_version: v0.52.0

        - name: initialise tflint
          run: tflint --init
          working-directory: infra

        - name: run tflint
          run: tflint
          working-directory: infra

        - name: terraform plan
          run: terraform plan -var="image_tag=${{ github.sha }}"
          working-directory: infra

        - name: terraform apply
          run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}"
          working-directory: infra

        - name: post deploy check
          run: curl -sS --fail-with-body https://status.muminlabs.com/health
